### ISSUE TITLE
Updating with pywal changes?

### ISSUE THREAD

**Issue by dessalines** [Bluedrack28/vscode-wal#3]
I have a script that periodically changes my wallpaper, and reruns pywal based on that. Is there any way for this extension to pick up and reload when you run `wal -R` again?

**Comment by Bluedrack28** [comment]
I found [this](https://stackoverflow.com/questions/44390765/vscode-how-to-reload-theme-after-editing-its-style). It will maybe help you but I don't think there is an effective way to hot reload theme in vscode... Sorry. You may need to kill the process vscode and reload it with your script to make the change append faster, I think you can set the setting to vscode to autosafe every time you quit, that may work...

**Comment by dessalines** [comment]
A somewhat easy solution is to just use `Control+R` and reload a different project, which does update from the new pywal theme.
