### ISSUE TITLE
Light Theme?

### ISSUE THREAD

**Issue by fr3fou** [Bluedrack28/vscode-wal#5]
I really dig this, but I'd like to ask if it's possible to make two themes, one with a white background and another one which would be the "normal" one. I'm looking forward to seeing this done if possible! Also when will this be in the Marketplace?

**Comment by sambnh** [comment]
I'll take a look at this, however I'm not sure when or if I'll be able to complete this.

**Comment by Bluedrack28** [comment]
Commit merged
